config/routes.rb
Rails.application.routes.draw do
  resources :audiences
end

app/models/audience.rb
class Audience < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController
  before_action :set_audience, only: [:show, :edit, :update, :destroy]

  # GET /audiences
  # GET /audiences.json
  def index
    @audiences = Audience.all
  end

  # GET /audiences/1
  # GET /audiences/1.json
  def show
  end

  # GET /audiences/new
  def new
    @audience = Audience.new
  end

  # GET /audiences/1/edit
  def edit
  end

  # POST /audiences
  # POST /audiences.json
  def create
    @audience = Audience.new(audience_params)

    respond_to do |format|
      if @audience.save
        format.html { redirect_to @audience, notice: 'Audience was successfully created.' }
        format.json { render :show, status: :created, location: @audience }
      else
        format.html { render :new }
        format.json { render json: @audience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audiences/1
  # PATCH/PUT /audiences/1.json
  def update
    respond_to do |format|
      if @audience.update(audience_params)
        format.html { redirect_to @audience, notice: 'Audience was successfully updated.' }
        format.json { render :show, status: :ok, location: @audience }
      else
        format.html { render :edit }
        format.json { render json: @audience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audiences/1
  # DELETE /audiences/1.json
  def destroy
    @audience.destroy
    respond_to do |format|
      format.html { redirect_to audiences_url, notice: 'Audience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audience
      @audience = Audience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audience_params
      params.require(:audience).permit(:user_name, :user_email, :user_avatar_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/views/audiences/_form.html.erb
<%= form_for(@audience) do |f| %>
  <% if @audience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audience.errors.count, "error") %> prohibited this audience from being saved:</h2>

      <ul>
      <% @audience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_email %><br>
    <%= f.text_field :user_email %>
  </div>
  <div class="field">
    <%= f.label :user_avatar_url %><br>
    <%= f.text_field :user_avatar_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/audiences/edit.html.erb
<h1>Editing Audience</h1>

<%= render 'form' %>

<%= link_to 'Show', @audience %> |
<%= link_to 'Back', audiences_path %>

app/views/audiences/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>You're whatching a live video</title>
</head>
<body>
  <%= video_player src: { mp4: 'https://content.jwplatform.com/manifests/yp34SRmf.m3u8' }, controls: true %>
</body>
</html>

app/views/audiences/new.html.erb
<h1>New Audience</h1>

<%= render 'form' %>

<%= link_to 'Back', audiences_path %>

app/views/audiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @audience.user_name %>
</p>

<p>
  <strong>User email:</strong>
  <%= @audience.user_email %>
</p>

<p>
  <strong>User avatar url:</strong>
  <%= @audience.user_avatar_url %>
</p>

<%= link_to 'Edit', edit_audience_path(@audience) %> |
<%= link_to 'Back', audiences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Livenetshow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>